services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
    volumes:
      - .:/app
    env_file:
      - .env
    tty: true